name: Linting
on:
  pull_request:
    paths-ignore:
      - '**.sh'
      - 'Dockerfile'
      - '**.y*ml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'

  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
